### ISSUE TITLE
Rewrite it in english

### ISSUE THREAD

**Issue by vcwild** [vcwild/qa4noobs#12]
Rewrite the project entirely in English.

- [ ] [Fundação](https://github.com/vcwild/qa4noobs/tree/main/docs/00-fundacao)
- [ ] [Abordagens](https://github.com/vcwild/qa4noobs/tree/main/docs/01-abordagens)
- [ ] [Tipos](https://github.com/vcwild/qa4noobs/tree/main/docs/02-tipos)
- [ ] [Administração de projetos](https://github.com/vcwild/qa4noobs/tree/main/docs/03-admin)
- [ ] [Execução](https://github.com/vcwild/qa4noobs/tree/main/docs/04-execucao)
- [ ] [Guide](https://github.com/vcwild/qa4noobs/tree/main/docs/guide)

**Comment by tvermaashutosh** [comment]
@vcwild Pease assign me this issue.
I will work very diligently on it.
