### ISSUE TITLE
Add English section

### ISSUE THREAD

**Issue by vcwild** [vcwild/qa4noobs#8]
Currently, the README of our project lacks an English section, which can make it difficult for non-native speakers or users who prefer English to understand and use our project effectively. To improve the accessibility and usability of our project, we should add an English section to the README.

Tasks:

 - [ ] Create the "English Documentation" section in the README.
 - [ ] Translate installation instructions into English.
 - [ ] Translate usage guidelines into English.
 - [ ] Translate the project description into English.

**Comment by Neel-07** [comment]
Hello @vcwild i'm ready to do this task, can you please assign me this task.

**Comment by vcwild** [comment]
@Neel-07 Thank you for your initiative. Please, kindly wait for the hacktoberfest event to start before assuming this issue.

**Comment by Neel-07** [comment]
hello @vcwild  made a pr to this issue, had a small request can you add hacktoberfest-accepted to this issue.
